- problem1:
  title: 問題1
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem2:
  title: 問題2 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem3:
  title: 問題3 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem4:
  title: 問題4 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem5:
  title: 問題5 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem6:
  title: 問題6 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem7:
  title: 問題7-1 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem8:
  title: 問題7-2 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem9:
  title: 問題7-3 
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem10:
  title: 問題8
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem11:
  title: 問題9
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem12:
  title: 問題10
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
