- problem1:
  title: 問題1 - これ解けたらすげぇ！
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem2:
  title: 問題2 - これ解けたらすげぇ！
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
- problem3:
  title: 問題3 - これ解けたらすげぇ！
  text: |
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
    まじパナイ問題っす！
